# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: database-postgre
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=databasetest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example

  app:
    image: flask-test
    build: 
      context: .
    depends_on:
      - db  
    restart: always
    ports:
      - 5000:5000